### ISSUE TITLE
JS code injected in pages fails in IE8

### ISSUE THREAD

**Issue by maxf** [datagovuk/dgu2#97]
The Phoenix channels code, automatically injected into app.js doesn't execute on IE8, unsurprisingly.
As of this writing the Service Manual is still requiring IE8 functional support, so we need to find a way to remove the offending JS code.

**Comment by rossjones** [comment]
The offending JS code is deps/phoenix/web/static/js/phoenix.js - we don't use it, but it is used by the live-reload in dev so if we're happy to lose that (background re-compilation still happens so cmd-r will work) we can just get brunch to exclude it.

**Comment by maxf** [comment]
I don't know if we need to worry about that now, anyway. Lots will break on IE8, including the search box components. I've been trying to polyfill it, but it'll be a bit of work to make it work (if it's possible at all).
Happy to close the issue for this prototype. wdyt?
